# Generated by Django 1.9.4 on 2016-03-27 22:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Example: 'legal-notice'. Each page must have a unique slug.", unique=True, verbose_name='Slug/URL')),
                ('title', models.CharField(help_text="Example: 'Legal notice'. The title is used for the entry in the menu. Do not use long titles.", max_length=255, verbose_name='Menu title')),
                ('weight', models.IntegerField(default=100, help_text='Use this for ordering. A higher number means that the entry appears further down in the menu.', verbose_name='Weight')),
                ('content', models.TextField(blank=True, help_text='You can use full HTML here.', verbose_name='Content (HTML)')),
                ('sitemap_priority', models.DecimalField(decimal_places=1, default=0.5, help_text='The sitemap is used by search engines: See <a href="http://www.sitemaps.org/protocol.html#prioritydef">Sitemap protocol</a>.', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Priority in the sitemap')),
                ('parent', models.ForeignKey(blank=True, help_text='If this field is empty, the page appears in the main menu at root level. Else the page is a subpage of its parent.', null=True, on_delete=django.db.models.deletion.CASCADE, to='NotarTH.FlatPage', verbose_name='Parent element')),
            ],
            options={
                'ordering': ('weight', 'slug'),
                'verbose_name_plural': 'Static Pages',
                'verbose_name': 'Static Page',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediafile', models.FileField(max_length=255, upload_to='', verbose_name='File')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded on')),
            ],
            options={
                'ordering': ('-uploaded_on',),
                'verbose_name_plural': 'Files',
                'verbose_name': 'File',
            },
        ),
    ]
