# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NotarTH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text="Example: 'The legal details of our business.'. The subtitle is used as subheading at the top of the page.", max_length=255, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If this field is empty, the page appears in the main menu at root level. Else the page is a subpage of its parent.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='NotarTH.FlatPage', verbose_name='Parent element'),
        ),
    ]
