# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=100, help_text='Use this for ordering. A higher number means that the slide appears further right in the carousel.', verbose_name='Weight')),
                ('caption', models.CharField(blank=True, help_text="Example: 'Trust me'.", max_length=255, verbose_name='Caption')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notar.MediaFile', verbose_name='File')),
            ],
            options={
                'ordering': ('weight',),
                'verbose_name_plural': 'Carousel slides',
                'verbose_name': 'Carousel slide',
            },
        ),
    ]
