# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notar', '0002_carouselslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslide',
            name='slide',
            field=models.ForeignKey(help_text='Use an 1900x1080 image (e. g. JPG or PNG) here.', on_delete=django.db.models.deletion.CASCADE, to='Notar.MediaFile', verbose_name='File'),
        ),
    ]
