# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notar', '0003_auto_20160330_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='submenu_title',
            field=models.CharField(blank=True, help_text="Example: 'All services'. The submenu title is used for the entry in the submenu and only if the page has children. Do not use long titles.", max_length=255, verbose_name='Submenu title'),
        ),
    ]
