"""
Django settings for Notar project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import textwrap

from django.utils.translation import gettext_lazy as _


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '<%= secretKey %>'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'constance',
    'constance.backends.database',
    'Notar',
]

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Notar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'constance.context_processors.config',
                'Notar.context_processors.flatpages',
                'Notar.context_processors.carousel_slides',
            ],
        },
    },
]

WSGI_APPLICATION = '<%= outputDirectoryBaseName %>.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(os.path.dirname(__file__), 'db.sqlite3')
    }
}

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'Notar',
#        'USER': 'Notar',
#        'PASSWORD': '...',
#        'HOST': 'localhost',
#        'PORT': '5432'
#    }
# }


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGES = [
    ('de', _('German')),
]

LANGUAGE_CODE = 'de-DE'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

if DEBUG:
    STATICFILES_DIRS = [os.path.join(os.path.dirname(__file__), 'static')]
else:
    STATIC_ROOT = os.path.join(os.path.dirname(__file__), 'static')


# User uploaded files
# https://docs.djangoproject.com/en/1.9/topics/files/

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(os.path.dirname(__file__), 'media')


# Constance - Dynamic Django settings
# http://django-constance.readthedocs.org/

DEFAULT_HOME_CONTENT = textwrap.dedent(
    """
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Welcome to my website
            </h1>
        </div>
        <div class="col-md-6">
            <p>Welcome to the website of John Doe.</p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Corporis, omnis doloremque non cum id reprehenderit,
                quisquam totam aspernatur tempora minima unde aliquid ea
                culpa sunt. Reiciendis quia dolorum ducimus unde.
            </p>
        </div>
        <div class="col-md-6">
            <img class="img-responsive" src="http://placehold.it/700x450" alt="">
        </div>
    </div><!-- /.row -->

    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">
                Top News
            </h2>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-star"></i> Top News One</h4>
                </div>
                <div class="panel-body">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit. Itaque, optio corporis quae nulla aspernatur in
                        alias at numquam rerum ea excepturi expedita tenetur
                        assumenda voluptatibus eveniet incidunt dicta nostrum
                        quod?
                    </p>
                    <a href="#" class="btn btn-default">Get More</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-star"></i> Top News Two</h4>
                </div>
                <div class="panel-body">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit. Itaque, optio corporis quae nulla aspernatur in
                        alias at numquam rerum ea excepturi expedita tenetur
                        assumenda voluptatibus eveniet incidunt dicta nostrum
                        quod?
                    </p>
                    <a href="#" class="btn btn-default">Get More</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-star"></i> Top News Three</h4>
                </div>
                <div class="panel-body">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit. Itaque, optio corporis quae nulla aspernatur in
                        alias at numquam rerum ea excepturi expedita tenetur
                        assumenda voluptatibus eveniet incidunt dicta nostrum
                        quod?
                    </p>
                    <a href="#" class="btn btn-default">Get More</a>
                </div>
            </div>
        </div>
    </div><!-- /.row -->

    <hr>

    <div class="well">
        <div class="row">
            <div class="col-md-8">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing
                    elit. Molestias, expedita, saepe, vero rerum deleniti
                    beatae veniam harum neque nemo praesentium cum alias
                    asperiores commodi.
                </p>
            </div>
            <div class="col-md-4">
                <a class="btn btn-lg btn-default btn-block" href="#">Get in touch</a>
            </div>
        </div><!-- /.row -->
    </div><!-- /.well -->
    """)

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_CONFIG = {
    'SITE_AUTHOR': (
        'John Doe',
        "The value for the top bar brand, the copyright notice and the HTML "
        "meta tag 'author'."),
    'SITE_TITLE': (
        'Title',
        'The value for the title of the page shown on the browser tab.'),
    'SITE_DESCRIPTION': (
        'Description',
        "The value for the HTML meta tag 'description'. This is used by "
        "search engines."),
    'SITE_KEYWORDS': (
        'Keyword1,Keyword2,Keyword3',
        "The value for the HTML meta tag 'keywords'. This is used by search "
        "engines."),
    'HOME_CONTENT': (
        DEFAULT_HOME_CONTENT,
        "The HTML content of the home page."),
}
